
 name: deploy-manifest

on: 
 push:
   branches:
     - main
   paths:
     - 'auth/**'
     
jobs: 
 build:
   runs-on: ubuntu-latest
   steps: 
     - name: Checkout code
       uses: actions/checkout@v2
     - uses: digitalocean/action-doctl@v2
       with:
        token: ${{ secrets.DIGITALOCEAN_TOKEN }}
     - run: doctl kubernetes cluster kubeconfig save jobee
     - run: kubectl apply -f infra/k8s
 
