apiVersion: skaffold/v2alpha3
kind: Config

deploy:
  kubectl:
    manifests:
      
      - infra/k8s/*

build:
  local:
    push: false
  artifacts:
    - image: ranjithp007/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual: 
        - src: 'src/**/*.ts'
          dest: .
    - image: ranjithp007/user
      context: user
      docker:
        dockerfile: Dockerfile
      sync:
        manual: 
        - src: 'src/**/*.ts'
          dest: .
