apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec: 
      containers:
        - name: auth    
          image: ranjithp007/auth
          env:
            - name: MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: auth-mongo
                  key:  MONGO_URL
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: JWT_KEY
            - name: ADMIN_CREDENTIAL
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: ADMIN_CREDENTIAL
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: SECRET_KEY
            - name: EMAILID
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: EMAILID
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: PASSWORD

---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000                  
