apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-depl
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: chat
  template:
    metadata:
      labels:
        app: chat
    spec: 
      containers:
        - name: chat    
          image: ranjithp007/chat
          env:
            - name: MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: chat-mongo
                  key:  MONGO_URL
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: chat-srv
spec:
  selector:
    app: chat
  ports:
    - name: chat
      protocol: TCP
      port: 3000
      targetPort: 3000