apiVersion: apps/v1
kind: Deployment
metadata:
  name: company-depl
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: company
  template:
    metadata:
      labels:
        app: company
    spec: 
      containers:
        - name: company   
          image: ranjithp007/company
          env:
            - name: MONGO_URL
              value: 'mongodb://company-mongo-srv:27017/company'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: JWT_KEY  
---
apiVersion: v1
kind: Service
metadata:
  name: company-srv
spec:
  selector:
    app: company
  ports:
    - name: company
      protocol: TCP
      port: 3000
      targetPort: 3000
