apiVersion: apps/v1
kind: Deployment
metadata:
  name: photo-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: photo
  template:
    metadata:
      labels:
        app: photo
    spec:
      containers:
        - name: photo
          image: ranjithp007/photo
          env:
            - name: AWS_BUCKET_NAME
              valueFrom:
                configMapKeyRef:
                  name: photo-config
                  key: AWS_BUCKET_NAME
            - name: AWS_BUCKET_REGION
              valueFrom:
                configMapKeyRef:
                  name: photo-config
                  key: AWS_BUCKET_REGION
            - name: AWS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: AWS_ACCESS_KEY
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: AWS_SECRET_ACCESS_KEY

---
apiVersion: v1
kind: Service
metadata:
  name: photo-srv
spec:
  selector:
    app: photo
  ports:
    - name: photo
      protocol: TCP
      port: 3000
      targetPort: 3000