name: deploy-company

on: 
 push:
   branches:
     - main
   paths:
     - 'company/**'
     
jobs: 
 build:
   runs-on: ubuntu-latest
   steps: 
     - name: Checkout code
       uses: actions/checkout@v2
     - name: Build Docker Image
       run: |
         cd company
         docker build -t ranjithp007/company .
     - name: Login to Docker Hub
       run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
       env:
         DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
         DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
     - name: Push Docker Image
       run: docker push ranjithp007/company
     - uses: digitalocean/action-doctl@v2
       with:
        token: ${{ secrets.DIGITALOCEAN_TOKEN }}
     - run: doctl kubernetes cluster kubeconfig save jobeee
     - run: kubectl rollout restart deployment company-depl
   
   
